# Generated by Django 4.0.3 on 2022-07-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.TextField()),
                ('user_type', models.IntegerField(choices=[(1, 'Doctor'), (2, 'Agape User')])),
            ],
        ),
    ]
