# Generated by Django 4.0.3 on 2022-04-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_doctor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='category',
            field=models.CharField(choices=[(1, 'Doctor Related'), (2, 'App Related')], default=2, max_length=30),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[(1, 'Read'), (1, 'Unread')], default=1, max_length=30),
        ),
    ]
