# Generated by Django 4.0.3 on 2022-04-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_userfeedback_category_userfeedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltips',
            name='sourced_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PatientSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.agapeuser')),
                ('viewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPrescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.doctor')),
                ('prescription_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.agapeuser')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.agapeuser')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.doctor')),
            ],
        ),
    ]
