# Generated by Django 4.0.3 on 2022-04-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_doctor_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[(4, 'Pending'), (2, 'Ongoing'), (1, 'Complete'), (3, 'Cancelled')], default=4, max_length=30),
        ),
    ]
