# Generated by Django 4.0.3 on 2022-04-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_doctor_id_number_doctor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='self_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
