# Generated by Django 4.0.3 on 2022-04-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_certificate',
            field=models.FileField(default=False, upload_to='license/'),
        ),
    ]
