# Generated by Django 4.0.3 on 2022-05-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_doctor_experience_years_doctor_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='My appointment', max_length=50),
        ),
        migrations.CreateModel(
            name='AppointmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.appointment')),
            ],
        ),
    ]
