# Generated by Django 4.0.3 on 2022-05-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_appointment_title_appointmenttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(4, 'Pending'), (2, 'Ongoing'), (1, 'Complete'), (3, 'Cancelled')], default=4),
        ),
    ]
