# Generated by Django 4.0.3 on 2022-05-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='category',
            field=models.IntegerField(choices=[(1, 'Doctor Related'), (2, 'App Related')], default=2),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='status',
            field=models.IntegerField(choices=[(1, 'Read'), (1, 'Unread')], default=1),
        ),
    ]
