# Generated by Django 4.0.3 on 2022-04-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_doctor_license_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_certificate',
            field=models.FileField(upload_to='license/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
