# Generated by Django 4.0.3 on 2022-05-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_delete_appointmenttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
