# Generated by Django 4.0.3 on 2022-05-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_appointmentrequest_delete_appointmentrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='symptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.patientsymptoms'),
        ),
    ]
