# Generated by Django 4.0.3 on 2022-05-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_appointmentrequest_symptoms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientsymptoms',
            options={'verbose_name_plural': 'Patient Symptoms'},
        ),
    ]
