# Generated by Django 4.0.3 on 2022-05-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_patientsymptoms_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
    ]
