# Generated by Django 4.0.3 on 2022-05-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_appointmentrequest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_verified', 'is_available'], name='staff_docto_is_veri_509f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_verified'], name='staff_docto_is_veri_e4e8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_available'], name='staff_docto_is_avai_335fcc_idx'),
        ),
    ]
