# Generated by Django 4.0.3 on 2022-06-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_doctor_staff_docto_is_veri_509f3e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_category', models.IntegerField(choices=[(1, 'DOCTOR'), (2, 'PATIENT')])),
                ('recipient_id', models.IntegerField()),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
