# Generated by Django 4.0.3 on 2022-06-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_medicalreport_delete_doctorprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='persistence_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
