# Generated by Django 4.0.3 on 2022-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_appointmentrequest_persistence_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsymptoms',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patientsymptoms',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
