# Generated by Django 4.0.3 on 2022-06-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_patientsymptoms_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='persistence_period',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
