# Generated by Django 4.0.3 on 2022-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_alter_appointmentrequest_persistence_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsymptoms',
            name='persistence_period',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
