# Generated by Django 4.0.3 on 2022-06-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_patientsymptoms_persistence_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='agapeuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
