# Generated by Django 4.0.3 on 2022-06-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_agapeuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_profile_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_profile_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='client_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='client_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='client_profile_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='doctor_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='doctor_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='doctor_profile_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
