# Generated by Django 4.0.3 on 2022-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_appointment_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
