# Generated by Django 4.0.3 on 2022-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_appointment_appointment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='self_description',
            field=models.TextField(blank=True, default='No description provided.'),
        ),
    ]
