# Generated by Django 4.0.3 on 2022-06-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_alter_doctor_self_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
