# Generated by Django 4.0.3 on 2022-06-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_appointmentrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.appointment'),
        ),
    ]
