# Generated by Django 4.0.3 on 2022-06-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_remove_medicalreport_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agapeuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agapeuser',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
