# Generated by Django 4.0.3 on 2022-06-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_agapeuser_age_agapeuser_gender_doctor_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agapeuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
