# Generated by Django 4.0.3 on 2022-06-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_alter_agapeuser_gender_alter_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='back_id_part',
            field=models.ImageField(blank=True, null=True, upload_to='back_id_part/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='front_id_part',
            field=models.ImageField(blank=True, null=True, upload_to='front_id_part/'),
        ),
    ]
