# Generated by Django 4.0.3 on 2022-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_doctor_back_id_part_doctor_front_id_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
