# Generated by Django 4.0.3 on 2022-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_doctor_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'APPOINTMENT'), (2, 'AGAPE INFO'), (3, 'BIRTHDAY WISH')], default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
