# Generated by Django 4.0.3 on 2022-07-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0035_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agapeuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
