# Generated by Django 4.0.3 on 2022-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agape_sockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsocketmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'READ'), (2, 'UNREAD')], default=2),
        ),
    ]
