# Generated by Django 4.0.3 on 2022-05-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agape_sockets', '0003_testsocketmonitor_testsocketmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsocketmonitor',
            options={'verbose_name': 'Test User Monitor'},
        ),
    ]
