# Generated by Django 4.0.3 on 2022-05-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agape_sockets', '0006_agapeuser1_patientsymptoms1_doctor1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsymptoms1',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agape_sockets.agapeuser1'),
        ),
        migrations.AlterField(
            model_name='patientsymptoms1',
            name='viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agape_sockets.doctor1'),
        ),
    ]
