# Generated by Django 4.0.3 on 2022-05-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agape_sockets', '0007_alter_patientsymptoms1_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor1',
            name='category',
        ),
    ]
