# Generated by Django 4.0.3 on 2022-06-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agape_sockets', '0009_remove_doctor1_created_at_remove_doctor1_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest1',
            name='client',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest1',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest1',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='doctor1',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='patientsymptoms1',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientsymptoms1',
            name='viewed_by',
        ),
        migrations.DeleteModel(
            name='AgapeUser1',
        ),
        migrations.DeleteModel(
            name='AppointmentRequest1',
        ),
        migrations.DeleteModel(
            name='Doctor1',
        ),
        migrations.DeleteModel(
            name='PatientSymptoms1',
        ),
    ]
